[".config/zsh/omz"]
    type = "git-repo"
    url = "https://github.com/ohmyzsh/ohmyzsh.git"
    refreshPeriod = "168h"
    clone.args = ["--depth", "1"]
    pull.args = ["--ff-only"]

[".config/zsh/omz_custom/themes/powerlevel10k"]
    type = "git-repo"
    url = "https://github.com/romkatv/powerlevel10k.git"
    refreshPeriod = "168h"
    clone.args = ["--depth", "1"]
    pull.args = ["--ff-only"]

[".config/zsh/omz_custom/plugins/fast-syntax-highlighting"]
    type = "git-repo"
    url = "https://github.com/zdharma-continuum/fast-syntax-highlighting.git"
    refreshPeriod = "168h"
    clone.args = ["--depth", "1"]
    pull.args = ["--ff-only"]

[".config/tmux/plugins/tpm"]
    type = "git-repo"
    url = "https://github.com/tmux-plugins/tpm.git"
    refreshPeriod = "168h"
    clone.args = ["--depth", "1"]
    pull.args = ["--ff-only"]
